// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimePlanner.Dashboard.Data.SqlServer;

#nullable disable

namespace TimePlanner.Dashboard.Data.SqlServer.Migrations.App
{
    [DbContext(typeof(SqlServerAppDbContext))]
    partial class SqlServerAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalAccountName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("LocalAccountName")
                        .IsUnique()
                        .HasFilter("[LocalAccountName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"ParentCategoryId\" IS NULL");

                    b.HasIndex("ParentCategoryId", "Name")
                        .IsUnique()
                        .HasFilter("[ParentCategoryId] IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Colour = "#6366F1",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Meeting",
                            SortOrder = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            Colour = "#7C3AED",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Coding",
                            SortOrder = 2
                        },
                        new
                        {
                            CategoryId = 4,
                            Colour = "#EA580C",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Email",
                            SortOrder = 4
                        },
                        new
                        {
                            CategoryId = 5,
                            Colour = "#71717A",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Admin",
                            SortOrder = 5
                        },
                        new
                        {
                            CategoryId = 6,
                            Colour = "#DB2777",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Design",
                            SortOrder = 3
                        },
                        new
                        {
                            CategoryId = 7,
                            Colour = "#0891B2",
                            IsArchived = false,
                            IsBillable = false,
                            Name = "Learning",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.CheckInSkip", b =>
                {
                    b.Property<int>("CheckInSkipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInSkipId"));

                    b.Property<int>("DaySessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SkippedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CheckInSkipId");

                    b.HasIndex("DaySessionId");

                    b.ToTable("CheckInSkips");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.DaySession", b =>
                {
                    b.Property<int>("DaySessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DaySessionId"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DaySessionId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"EndedAt\" IS NULL");

                    b.ToTable("DaySessions", t =>
                        {
                            t.HasCheckConstraint("CK_DaySessions_EndAfterStart", "\"EndedAt\" IS NULL OR \"EndedAt\" >= \"StartedAt\"");
                        });
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.HasIndex("CompanyId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.SessionPause", b =>
                {
                    b.Property<int>("SessionPauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionPauseId"));

                    b.Property<int>("DaySessionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionPauseId");

                    b.HasIndex("DaySessionId")
                        .IsUnique()
                        .HasFilter("\"EndedAt\" IS NULL");

                    b.ToTable("SessionPauses", t =>
                        {
                            t.HasCheckConstraint("CK_SessionPauses_EndAfterStart", "\"EndedAt\" IS NULL OR \"EndedAt\" >= \"StartedAt\"");
                        });
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<int>("TimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeEntryId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TimeEntryId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "StartTime");

                    b.ToTable("TimeEntries", t =>
                        {
                            t.HasCheckConstraint("CK_TimeEntries_EndAfterStart", "\"EndTime\" > \"StartTime\"");
                        });
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.TimeSheet", b =>
                {
                    b.Property<int>("TimeSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSheetId"));

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TimeSheetId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.UserSettings", b =>
                {
                    b.Property<int>("UserSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSettingsId"));

                    b.Property<int>("CheckInIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<double>("DailyGoalHours")
                        .HasColumnType("float");

                    b.Property<string>("IgnoredCheckInAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IgnoredCheckInMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("LunchEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("LunchStart")
                        .HasColumnType("time");

                    b.Property<int>("MaxSkipsPerDay")
                        .HasColumnType("int");

                    b.Property<int>("MaxSnoozes")
                        .HasColumnType("int");

                    b.Property<int>("SnoozeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserSettingsId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings", t =>
                        {
                            t.HasCheckConstraint("CK_UserSettings_Goal", "\"DailyGoalHours\" BETWEEN 0.5 AND 24");

                            t.HasCheckConstraint("CK_UserSettings_Ignored", "\"IgnoredCheckInMinutes\" BETWEEN 1 AND 60");

                            t.HasCheckConstraint("CK_UserSettings_Interval", "\"CheckInIntervalMinutes\" BETWEEN 5 AND 480");

                            t.HasCheckConstraint("CK_UserSettings_Lunch", "\"LunchStart\" < \"LunchEnd\"");

                            t.HasCheckConstraint("CK_UserSettings_MaxSkips", "\"MaxSkipsPerDay\" BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_UserSettings_MaxSnoozes", "\"MaxSnoozes\" BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_UserSettings_Snooze", "\"SnoozeMinutes\" BETWEEN 1 AND 60");
                        });
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.WorkTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("AssignedUserID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("AssignedUserID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProjectID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Category", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.CheckInSkip", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.DaySession", "DaySession")
                        .WithMany()
                        .HasForeignKey("DaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaySession");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.DaySession", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Project", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.SessionPause", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.DaySession", "DaySession")
                        .WithMany("Pauses")
                        .HasForeignKey("DaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaySession");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.WorkTask", "Task")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.TimeSheet", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "User")
                        .WithMany("TimeSheets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "User")
                        .WithOne("Settings")
                        .HasForeignKey("TimePlanner.Core.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.WorkTask", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimePlanner.Core.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimePlanner.Core.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Category");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Settings");

                    b.Navigation("TimeEntries");

                    b.Navigation("TimeSheets");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.DaySession", b =>
                {
                    b.Navigation("Pauses");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.WorkTask", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
