// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimePlanner.Core.Data;

#nullable disable

namespace TimePlanner.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002171144_AddCategoryArchive")]
    partial class AddCategoryArchive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalAccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("LocalAccountName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"ParentCategoryId\" IS NULL");

                    b.HasIndex("ParentCategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Colour = "#6366F1",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Meeting",
                            SortOrder = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            Colour = "#7C3AED",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Coding",
                            SortOrder = 2
                        },
                        new
                        {
                            CategoryId = 4,
                            Colour = "#EA580C",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Email",
                            SortOrder = 4
                        },
                        new
                        {
                            CategoryId = 5,
                            Colour = "#71717A",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Admin",
                            SortOrder = 5
                        },
                        new
                        {
                            CategoryId = 6,
                            Colour = "#DB2777",
                            IsArchived = false,
                            IsBillable = true,
                            Name = "Design",
                            SortOrder = 3
                        },
                        new
                        {
                            CategoryId = 7,
                            Colour = "#0891B2",
                            IsArchived = false,
                            IsBillable = false,
                            Name = "Learning",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.CheckInSkip", b =>
                {
                    b.Property<int>("CheckInSkipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaySessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SkippedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CheckInSkipId");

                    b.HasIndex("DaySessionId");

                    b.ToTable("CheckInSkips");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.DaySession", b =>
                {
                    b.Property<int>("DaySessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DaySessionId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"EndedAt\" IS NULL");

                    b.ToTable("DaySessions");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectID");

                    b.HasIndex("CompanyId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.SessionPause", b =>
                {
                    b.Property<int>("SessionPauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaySessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionPauseId");

                    b.HasIndex("DaySessionId")
                        .IsUnique()
                        .HasFilter("\"EndedAt\" IS NULL");

                    b.ToTable("SessionPauses");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<int>("TimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeEntryId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.TimeSheet", b =>
                {
                    b.Property<int>("TimeSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeSheetId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.UserSettings", b =>
                {
                    b.Property<int>("UserSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckInIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DailyGoalHours")
                        .HasColumnType("REAL");

                    b.Property<string>("IgnoredCheckInAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IgnoredCheckInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("LunchEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("LunchStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxSkipsPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSnoozes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnoozeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserSettingsId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.WorkTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedUserID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.HasIndex("AssignedUserID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProjectID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Category", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.CheckInSkip", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.DaySession", "DaySession")
                        .WithMany()
                        .HasForeignKey("DaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaySession");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.DaySession", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Project", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.SessionPause", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.DaySession", "DaySession")
                        .WithMany("Pauses")
                        .HasForeignKey("DaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaySession");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.WorkTask", "Task")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.TimeSheet", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "User")
                        .WithMany("TimeSheets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "User")
                        .WithOne("Settings")
                        .HasForeignKey("TimePlanner.Core.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.WorkTask", b =>
                {
                    b.HasOne("TimePlanner.Core.Domain.Entities.AppUser", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimePlanner.Core.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimePlanner.Core.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Category");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Settings");

                    b.Navigation("TimeEntries");

                    b.Navigation("TimeSheets");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.DaySession", b =>
                {
                    b.Navigation("Pauses");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TimePlanner.Core.Domain.Entities.WorkTask", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
